version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: dbpostgres
    restart: always
    environment:
      POSTGRES_USER: logisticlab
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dblogisticlab
    ports:
      - "5432:5432"
    networks:
      - logisticlab

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - ./.docker-data/grafana:/var/lib/grafana
    ports:
      - "4000:3000"
    depends_on:
      - postgres
    networks:
      - logisticlab

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: logisticlab
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./.docker-data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - logisticlab

networks:
  logisticlab:
    driver: bridge
